### ISSUE TITLE
ClassFormatException for RootDescriber during Maven Build

### ISSUE THREAD

**Issue by mmichaelis** [mmichaelis/describeme#7]
When building DescribeMe with Maven 3.2 the following `ClassFormatException` is reported again and again:

```
[INFO] --- maven-site-plugin:3.4:site (default-site) @ describeme-library ---
...
[INFO] Generating "Dependencies" report         --- maven-project-info-reports-plugin:2.8:dependencies
[WARNING] Unable to process class com/github/mmichaelis/describeme/core/RootDescriber.class in JarAnalyzer File D:\Documents\GitHub\describeme\parent\core\target\describeme-core-1.0.0-SNAPSHOT.jar
org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 18
    at org.apache.bcel.classfile.Constant.readConstant(Constant.java:146)
    at org.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:67)
    at org.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:222)
    at org.apache.bcel.classfile.ClassParser.parse(ClassParser.java:136)
    at org.apache.maven.shared.jar.classes.JarClassesAnalysis.analyze(JarClassesAnalysis.java:92)
    at org.apache.maven.report.projectinfo.dependencies.Dependencies.getJarDependencyDetails(Dependencies.java:259)
    at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.hasSealed(DependenciesRenderer.java:1516)
    at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyFileDetails(DependenciesRenderer.java:535)
    at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:258)
    at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:83)
    at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:201)
    at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
    at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:224)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:311)
...
```

**Comment by mmichaelis** [comment]
This seems to be related to:
- [[MPIR-142] Dependency report fails to generate if dependencies contain com.ibm.icu:icu4j:2.6.1](https://jira.codehaus.org/browse/MPIR-142)

which again refers to
- [#3209 (LocaleElement_zh__PINYIN failure)](http://icu-project.org/trac/ticket/3209)

First naive tries to override the ICU `com.ibm.icu:icu4j` dependency for maven-project-info-reports-plugin and/or maven-site-plugin did not provide any difference.

**Comment by mmichaelis** [comment]
Path to icu4j (Reverse dependency tree from my Maven Repository):
- `com.ibm.icu:icu4j`
  - `xom:xom`
    - `jaxen:jaxen`
      - `dom4j:dom4j`
        - **`org.apache.maven.plugins:maven-pmd-plugin`**
        - ...
      - `jdom:jdom`
      - `cobertura:cobertura`
      - `pmd:pmd` - explicitly excludes icu4j
      - **`org.apache.maven.plugins:maven-assembly-plugin`**
      - **`org.apache.maven.plugins:maven-eclipse-plugin`**

Next tree elements missing.

Findbugs and PMD just exclude `com.ibm.icu:icu4j`.

**Comment by mmichaelis** [comment]
Giving up. Tried to exclude icu4j for different plugins (assuming that this is the source) - but unfortunately this problem is old and known - but not solved for many years :disappointed:
